=== mapsforge/mapsforge/resources/renderTheme-v5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:tns="http://mapsforge.org/renderTheme" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified" targetNamespace="http://mapsforge.org/renderTheme" xml:lang="en">
    <!-- attribute types -->
    <xs:simpleType name="cap">
        <xs:restriction base="xs:string">
            <xs:enumeration value="butt" />
            <xs:enumeration value="round" />
            <xs:enumeration value="square" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="position">
        <xs:restriction base="xs:string">
            <xs:enumeration value="auto" />
            <xs:enumeration value="center" />
            <xs:enumeration value="below" />
            <xs:enumeration value="below_left" />
            <xs:enumeration value="below_right" />
            <xs:enumeration value="above" />
            <xs:enumeration value="above_left" />
            <xs:enumeration value="above_right" />
            <xs:enumeration value="left" />
            <xs:enumeration value="right" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="closed">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes" />
            <xs:enumeration value="no" />
            <xs:enumeration value="any" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="color">
        <xs:annotation>
            <xs:documentation>Supported formats are #RRGGBB and #AARRGGBB.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="#([0-9a-fA-F]{6}|[0-9a-fA-F]{8})" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="display">
        <xs:restriction base="xs:string">
            <xs:enumeration value="always" />
            <xs:enumeration value="never" />
            <xs:enumeration value="ifspace" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="elementList">
        <xs:restriction base="xs:string">
            <xs:enumeration value="node" />
            <xs:enumeration value="way" />
            <xs:enumeration value="any" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fontFamily">
        <xs:restriction base="xs:string">
            <xs:enumeration value="default" />
            <xs:enumeration value="monospace" />
            <xs:enumeration value="sans_serif" />
            <xs:enumeration value="serif" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fontStyle">
        <xs:restriction base="xs:string">
            <xs:enumeration value="bold" />
            <xs:enumeration value="bold_italic" />
            <xs:enumeration value="italic" />
            <xs:enumeration value="normal" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="linejoin">
        <xs:restriction base="xs:string">
            <xs:enumeration value="miter" />
            <xs:enumeration value="round" />
            <xs:enumeration value="bevel" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nonNegativeFloat">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="0" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="scale">
        <xs:restriction base="xs:string">
            <xs:enumeration value="all" />
            <xs:enumeration value="none" />
            <xs:enumeration value="stroke" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="src">
        <xs:restriction base="xs:string">
            <xs:pattern value="((jar|file|assets):)?.+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="strokeDasharray">
        <xs:restriction base="xs:string">
            <xs:pattern
                value="([0-9]+(\.[0-9]+)? *, *[0-9]+(\.[0-9]+)? *, *)*[0-9]+(\.[0-9]+)? *, *[0-9]+(\.[0-9]+)?" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="textKey">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ele" />
            <xs:enumeration value="addr:housenumber" />
            <xs:enumeration value="name" />
            <xs:enumeration value="ref" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="area">
        <xs:attribute name="cat" type="xs:string" use="optional" />
        <xs:attribute name="src" type="tns:src" use="optional" />
        <xs:attribute name="symbol-width" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="symbol-height" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="symbol-percent" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="fill" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="scale" default="stroke" type="tns:scale" use="optional" />
        <xs:attribute name="stroke" default="#00000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke-width" default="0" type="tns:nonNegativeFloat" use="optional" />
    </xs:complexType>

    <xs:complexType name="caption">
        <xs:attribute name="cat" type="xs:string" use="optional" />
        <xs:attribute name="priority" default="0" type="xs:integer" use="optional" />
        <xs:attribute name="k" type="tns:textKey" use="required" />
        <xs:attribute name="display" default="ifspace" type="tns:display" use="optional" />
        <xs:attribute name="dy" default="0" type="xs:float" use="optional" />
        <xs:attribute name="font-family" default="default" type="tns:fontFamily" use="optional" />
        <xs:attribute name="font-style" default="normal" type="tns:fontStyle" use="optional" />
        <xs:attribute name="font-size" default="0" type="tns:nonNegativeFloat" use="optional" />
        <xs:attribute name="fill" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke-width" default="0" type="tns:nonNegativeFloat" use="optional" />
        <xs:attribute name="position" default="auto" type="tns:position" use="optional" />
        <xs:attribute name="symbol-id" type="xs:string" use="optional" />
    </xs:complexType>

    <!-- style menu cat element -->
    <xs:complexType name="cat">
        <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="circle">
        <xs:attribute name="cat" type="xs:string" use="optional" />
        <xs:attribute name="radius" type="tns:nonNegativeFloat" use="required" />
        <xs:attribute name="scale-radius" default="false" type="xs:boolean" use="optional" />
        <xs:attribute name="fill" default="#00000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke" default="#00000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke-width" default="0" type="tns:nonNegativeFloat" use="optional" />
    </xs:complexType>

    <!-- style menu layer element -->
    <xs:complexType name="layer">
        <xs:sequence maxOccurs="1" minOccurs="0">
            <xs:element name="name" maxOccurs="unbounded" minOccurs="0" type="tns:name" />
            <xs:element name="cat" maxOccurs="unbounded" minOccurs="0" type="tns:cat" />
            <xs:element name="overlay" maxOccurs="unbounded" minOccurs="0" type="tns:overlay" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="parent" type="xs:string" use="optional" />
        <xs:attribute name="visible" default="false" type="xs:boolean" use="optional" />
        <xs:attribute name="enabled" default="false" type="xs:boolean" use="optional" />
    </xs:complexType>

    <xs:complexType name="line">
        <xs:attribute name="cat" type="xs:string" use="optional" />
        <xs:attribute name="src" type="tns:src" use="optional" />
        <xs:attribute name="symbol-width" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="symbol-height" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="symbol-percent" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="dy" default="0" type="xs:float" use="optional" />
        <xs:attribute name="scale" default="stroke" type="tns:scale" use="optional" />
        <xs:attribute name="stroke" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke-width" default="0" type="tns:nonNegativeFloat" use="optional" />
        <xs:attribute name="stroke-dasharray" type="tns:strokeDasharray" use="optional" />
        <xs:attribute name="stroke-linecap" default="round" type="tns:cap" use="optional" />
        <xs:attribute name="stroke-linejoin" default="round" type="tns:linejoin" use="optional" />
    </xs:complexType>

    <xs:complexType name="lineSymbol">
        <xs:attribute name="cat" type="xs:string" use="optional" />
        <xs:attribute name="display" default="ifspace" type="tns:display" use="optional" />
        <xs:attribute name="dy" default="0" type="xs:float" use="optional" />
        <xs:attribute name="scale" default="stroke" type="tns:scale" use="optional" />
        <xs:attribute name="src" type="tns:src" use="required" />
        <xs:attribute name="symbol-width" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="symbol-height" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="symbol-percent" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="align-center" default="false" type="xs:boolean" use="optional" />
        <xs:attribute name="priority" default="0" type="xs:integer" use="optional" />
        <xs:attribute name="repeat" default="false" type="xs:boolean" use="optional" />
        <xs:attribute name="repeat-gap" default="200" type="xs:float" use="optional" />
        <xs:attribute name="repeat-start" default="30" type="xs:float" use="optional" />
        <xs:attribute name="rotate" default="true" type="xs:boolean" use="optional" />
    </xs:complexType>

    <!-- style menu name element -->
    <xs:complexType name="name">
        <xs:attribute name="lang" type="xs:string" use="required" />
        <xs:attribute name="value" type="xs:string" use="required" />
    </xs:complexType>

    <!-- style menu overlay element -->
    <xs:complexType name="overlay">
        <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="pathText">
        <xs:attribute name="cat" type="xs:string" use="optional" />
        <xs:attribute name="display" default="ifspace" type="tns:display" use="optional" />
        <xs:attribute name="k" type="tns:textKey" use="required" />
        <xs:attribute name="dy" default="0" type="xs:float" use="optional" />
        <xs:attribute name="font-family" default="default" type="tns:fontFamily" use="optional" />
        <xs:attribute name="font-style" default="normal" type="tns:fontStyle" use="optional" />
        <xs:attribute name="font-size" default="0" type="tns:nonNegativeFloat" use="optional" />
        <xs:attribute name="fill" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="priority" default="0" type="xs:integer" use="optional" />
        <xs:attribute name="scale" default="stroke" type="tns:scale" use="optional" />
        <xs:attribute name="stroke" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke-width" default="0" type="tns:nonNegativeFloat" use="optional" />
        <xs:attribute name="repeat" default="true" type="xs:boolean" use="optional" />
        <xs:attribute name="repeat-gap" default="50" type="xs:float" use="optional" />
        <xs:attribute name="repeat-start" default="10" type="xs:float" use="optional" />
        <xs:attribute name="rotate" default="true" type="xs:boolean" use="optional" />
    </xs:complexType>

    <xs:complexType name="symbol">
        <xs:attribute name="id" type="xs:string" use="optional" />
        <xs:attribute name="cat" type="xs:string" use="optional" />
        <xs:attribute name="display" default="ifspace" type="tns:display" use="optional" />
        <xs:attribute name="priority" default="0" type="xs:integer" use="optional" />
        <xs:attribute name="src" type="tns:src" use="required" />
        <xs:attribute name="symbol-width" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="symbol-height" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="symbol-percent" type="xs:positiveInteger" use="optional" />
    </xs:complexType>

    <!-- rule elements -->
    <xs:complexType name="rule">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <!-- recursion to allow for nested rules -->
            <xs:element name="rule" type="tns:rule" />
            <xs:element name="area" type="tns:area" />
            <xs:element name="caption" type="tns:caption" />
            <xs:element name="circle" type="tns:circle" />
            <xs:element name="line" type="tns:line" />
            <xs:element name="lineSymbol" type="tns:lineSymbol" />
            <xs:element name="pathText" type="tns:pathText" />
            <xs:element name="symbol" type="tns:symbol" />
        </xs:choice>
        <xs:attribute name="e" type="tns:elementList" use="required" />
        <xs:attribute name="k" type="xs:string" use="required" />
        <xs:attribute name="v" type="xs:string" use="required" />
        <xs:attribute name="cat" type="xs:string" use="optional" />
        <xs:attribute name="closed" default="any" type="tns:closed" use="optional" />
        <xs:attribute name="zoom-min" default="0" type="xs:unsignedByte" use="optional" />
        <xs:attribute name="zoom-max" default="127" type="xs:unsignedByte" use="optional" />
    </xs:complexType>

    <xs:complexType name="hillShading">
        <xs:attribute name="zoom-min" type="xs:unsignedByte" use="optional" default="5" />
        <xs:attribute name="zoom-max" type="xs:unsignedByte" use="optional" default="17" />
        <xs:attribute name="magnitude" type="xs:unsignedByte" use="optional" default="64"/>
        <!-- customization unlikely to make any sense -->
        <xs:attribute name="layer" type="xs:unsignedByte" use="optional" default="5"/>
    </xs:complexType>


    <!-- rendertheme element -->
    <xs:complexType name="rendertheme">
        <xs:sequence maxOccurs="1" minOccurs="0">
            <xs:element name="stylemenu" maxOccurs="1" minOccurs="0" type="tns:stylemenu" />
            <xs:element name="rule" maxOccurs="unbounded" minOccurs="0" type="tns:rule" />
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element name="hillshading" type="tns:hillShading"/>
                <xs:element name="rule" type="tns:rule" />
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="version" fixed="5" type="xs:positiveInteger" />
        <xs:attribute name="map-background" default="#ffffff" type="tns:color" use="optional" />
        <xs:attribute name="map-background-outside" default="#ffffff" type="tns:color"
            use="optional" />
        <xs:attribute name="base-stroke-width" default="1" type="tns:nonNegativeFloat"
            use="optional" />
        <xs:attribute name="base-text-size" default="1" type="tns:nonNegativeFloat"
            use="optional" />
    </xs:complexType>

    <!-- stylemenu element -->
    <xs:complexType name="stylemenu">
        <xs:sequence maxOccurs="1" minOccurs="0">
            <xs:element name="layer" maxOccurs="unbounded" minOccurs="0" type="tns:layer" />
        </xs:sequence>
        <xs:attribute name="defaultvalue" type="xs:string" use="required" />
        <xs:attribute name="defaultlang" type="xs:string" use="required" />
        <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>

    <!-- root element -->
    <xs:element name="rendertheme" type="tns:rendertheme" />
</xs:schema>

=== mapsforge/mapsforge/mapsforge-themes/src/main/resources/assets/mapsforge/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<rendertheme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" map-background="#F8F8F8"
    map-background-outside="#DDDDDD" version="5" xmlns="http://mapsforge.org/renderTheme"
    xsi:schemaLocation="http://mapsforge.org/renderTheme https://raw.githubusercontent.com/mapsforge/mapsforge/master/resources/renderTheme-v5.xsd">

    <rule e="way" k="natural" v="issea|sea">
        <area fill="#B3DDFF" />
    </rule>

    <rule e="way" k="natural" v="nosea">
        <area fill="#F8F8F8" stroke="#F8F8F8" stroke-width="1.0" />
    </rule>

    <rule e="way" k="natural" v="land">
        <area fill="#BBF8F8F8" stroke="#F8F8F8" stroke-width="0.1" />
    </rule>

    <!-- landuse -->
    <rule e="way" k="landuse" v="military">
        <area src="jar:patterns/military.png" stroke="#e4e4e4" stroke-width="0.2" />
    </rule>
    <rule e="way" k="landuse" v="residential" zoom-min="14">
        <area fill="#BBDEDEDE" />
    </rule>
    <rule e="way" k="landuse" v="retail" zoom-min="14">
        <area fill="#BBF0CCF0" stroke="#E4E4E4" stroke-width="0.2" />
    </rule>

    <rule e="way" k="landuse" v="commercial|industrial|brownfield|railway|garages|construction"
        zoom-min="14">
        <area fill="#BBC9DDDD" stroke="#CCCCCC" stroke-width="0.2" />
    </rule>
    <rule e="way" k="amenity" v="school|college|university" zoom-min="14">
        <area fill="#F7F0D4" stroke="#CC7466" stroke-width="0.2" />
    </rule>
    <rule e="way" k="leisure|tourism|landuse"
        v="park|zoo|picnic_site|camp_site|caravan_site|recreation_ground" zoom-min="14">
        <area fill="#BBC7F1A3" stroke="#6FC18E" stroke-width="0.2" />
    </rule>
    <rule e="way" k="natural|landuse" v="forest|wood">
        <area fill="#A5CBA5" />
        <rule e="any" k="*" v="*" zoom-min="13">
            <rule e="any" k="wood" v="coniferous">
                <area src="jar:patterns/coniferous.svg" symbol-height="50" symbol-width="50" />
            </rule>
            <rule e="any" k="wood" v="deciduous">
                <area src="jar:patterns/deciduous.svg" symbol-height="50" symbol-width="50" />
            </rule>
            <rule e="any" k="wood" v="~|*">
                <area src="jar:patterns/coniferous_and_deciduous.svg" symbol-height="50"
                    symbol-width="50" />
            </rule>
        </rule>
    </rule>

    <rule e="way" k="landuse|natural" v="meadow|grassland" zoom-min="13">
        <area fill="#BBE6FFDB" stroke="#C6E6B8" stroke-width="0.1" />
    </rule>
    <rule e="way" k="landuse" v="field|farm|farmland|orchard|vineyard" zoom-min="13">
        <area src="jar:patterns/farmland.svg" symbol-height="70" symbol-width="70" />
    </rule>
    <rule e="way" k="natural" v="marsh|wetland|mud" zoom-min="13">
        <area fill="#88D0D9BF" stroke="#D0D9BF" stroke-width="0.1" />
        <area src="jar:patterns/swamp.svg" symbol-height="40" symbol-width="40" />
    </rule>
    <rule e="way" k="natural" v="beach|sand" zoom-min="14">
        <area fill="#FAEBB9" />
    </rule>
    <rule e="way" k="natural" v="rock|stone|bare_rock|bedrock" zoom-min="14">
        <area fill="#BBF1F1F1" stroke="#F1F1F1" stroke-width="0.1" />
        <area src="jar:patterns/hills.svg" symbol-height="40" symbol-width="40" />
    </rule>
    <rule e="way" k="natural" v="heath" zoom-min="14">
        <area fill="#BBEBF7E4" stroke="#EBF7E4" stroke-width="0.1" />
        <area src="jar:patterns/grass.svg" symbol-percent="30" />
    </rule>
    <rule e="way" k="natural" v="scrub" zoom-min="14">
        <area fill="#BBB7EBA4" stroke="#B7EBA4" stroke-width="0.1" />
        <area src="jar:patterns/scrub.svg" symbol-percent="50" />
    </rule>
    <rule e="way" k="natural" v="fell" zoom-min="14">
        <area fill="#BBE9FCE6" stroke="#E9FCE6" stroke-width="0.1" />
        <area src="jar:patterns/quarry.svg" symbol-height="90" symbol-width="90" />
    </rule>
    <rule e="way" k="natural" v="scree" zoom-min="14">
        <area fill="#BBF5F5F5" stroke="#F5F5F5" stroke-width="0.1" />
        <area src="jar:patterns/quarry.svg" symbol-height="90" symbol-width="90" />
    </rule>
    <rule e="way" k="natural" v="glacier" zoom-min="12">
        <area fill="#BBE0FFFF" stroke="#E0FFFF" stroke-width="0.8" />
    </rule>
    <rule e="way" k="landuse" v="landfill|quarry" zoom-min="14">
        <area fill="#CCF2EFE4" stroke="#9EA199" stroke-width="0.2" />
        <area src="jar:patterns/quarry.svg" symbol-height="90" symbol-width="90" />
    </rule>
    <rule e="way" k="landuse|leisure" v="garden|village_green|common|grass" zoom-min="14">
        <area fill="#BBC7F1A3" stroke="#6FC18E" stroke-width="0.2" />
    </rule>
    <rule e="way" k="landuse|leisure" v="allotments|greenfield|golf_course" zoom-min="15">
        <area fill="#BBD3EBD9" stroke="#6FC13D" stroke-width="0.2" />
    </rule>
    <rule e="way" k="landuse|amenity" v="cemetery|grave_yard" zoom-min="14">
        <area src="jar:patterns/cemetery.png" />
    </rule>
    <rule e="way" k="natural|landuse"
        v="land|beach|sand|rock|fell|meadow|grassland|heath|marsh|wetland|scree|scrub|forest|wood"
        zoom-min="15">
        <caption fill="#202020" font-family="serif" font-size="10" font-style="italic" k="name"
            stroke="#FFFFFF" stroke-width="0.1" />
    </rule>
    <rule e="way" k="landuse" v="landfill|quarry|vineyard|field|farm|farmland|orchard"
        zoom-min="16">
        <caption fill="#202020" font-family="serif" font-size="16" font-style="italic" k="name"
            stroke="#FFFFFF" stroke-width="0.1" />
    </rule>
    <rule e="way" k="landuse|leisure|amenity"
        v="grass|village_green|recreation_ground|military|park|garden|common|green|dog_park|allotments|cemetery|graveyard"
        zoom-min="16">
        <caption fill="#202020" font-family="serif" font-size="14" font-style="italic" k="name"
            stroke="#FFFFFF" stroke-width="2.0" />
    </rule>

    <!-- tunnels -->
    <rule e="way" k="tunnel" v="true|yes|culvert|building_passage|passage">
        <!-- highway tunnel -->
        <rule e="way" k="highway" v="steps|footway|path">
            <line stroke="#80CCCCCC" stroke-dasharray="0,12,4,0" stroke-linecap="butt"
                stroke-width="0.5" />
            <line stroke="#60999999" stroke-dasharray="12,4" stroke-linecap="butt"
                stroke-width="0.5" />
        </rule>
        <rule e="way" k="highway" v="track|bridleway|byway|cycleway|service">
            <line stroke="#80CCCCCC" stroke-dasharray="0,12,4,0" stroke-linecap="butt"
                stroke-width="1.0" />
            <line stroke="#60999999" stroke-dasharray="12,4" stroke-linecap="butt"
                stroke-width="1.0" />
        </rule>
        <rule e="way" k="highway"
            v="road|pedestrian|unclassified|residential|living_street|construction">
            <line stroke="#80CCCCCC" stroke-dasharray="0,12,4,0" stroke-linecap="butt"
                stroke-width="1.3" />
            <line stroke="#60999999" stroke-dasharray="12,4" stroke-linecap="butt"
                stroke-width="1.3" />
        </rule>
        <rule e="way" k="highway"
            v="tertiary|tertiary_link|secondary_link|primary_link|trunk_link|motorway_link|secondary|primary|trunk">
            <line stroke="#80CCCCCC" stroke-dasharray="0,16,6,0" stroke-linecap="butt"
                stroke-width="1.5" />
            <line stroke="#60999999" stroke-dasharray="16,6" stroke-linecap="butt"
                stroke-width="1.5" />
        </rule>
        <rule e="way" k="highway" v="motorway">
            <line stroke="#80CCCCCC" stroke-dasharray="0,20,8,0" stroke-linecap="butt"
                stroke-width="1.7" />
            <line stroke="#60999999" stroke-dasharray="20,8" stroke-linecap="butt"
                stroke-width="1.7" />
        </rule>

        <!-- railway tunnel -->
        <rule e="way" k="railway"
            v="tram|subway|light_rail|narrow_gauge|preserved|funicular|miniature|monorail">
            <line stroke="#60999999" stroke-dasharray="4,6" stroke-linecap="butt"
                stroke-width="0.25" />
        </rule>
        <rule e="way" k="railway" v="rail">
            <line stroke="#60999999" stroke-dasharray="6,6" stroke-linecap="butt"
                stroke-width="0.4" />
        </rule>
    </rule>


    <!-- waterbodies -->
    <rule e="any" k="*" v="*">
        <rule e="way" k="bridge" v="yes|true|viaduct|aqueduct|suspension|culvert|swing">
            <rule e="way" k="waterway" v="ditch|drain|stream">
                <line stroke="#333333" stroke-linecap="butt" stroke-width="1.6" />
                <line stroke="#EEEEEE" stroke-linecap="butt" stroke-width="1.2" />
            </rule>
            <rule e="way" k="waterway" v="canal|river">
                <line stroke="#333333" stroke-linecap="butt" stroke-width="2.0" />
                <line stroke="#EEEEEE" stroke-linecap="butt" stroke-width="1.6" />
            </rule>
        </rule>
        <rule e="way" k="waterway" v="ditch">
            <line stroke="#B3DDFF" stroke-width="0.6" />
        </rule>
        <rule e="way" k="waterway" v="drain">
            <line stroke="#B0B0B0" stroke-linecap="butt" stroke-width="0.7" />
            <line stroke="#B3DDFF" stroke-linecap="butt" stroke-width="0.5" />
        </rule>
        <rule e="way" k="waterway" v="canal">
            <line stroke="#B0B0B0" stroke-linecap="butt" stroke-width="1.1" />
            <line stroke="#B3DDFF" stroke-linecap="butt" stroke-width="0.9" />
        </rule>
        <rule e="way" k="waterway" v="stream">
            <line stroke="#B3DDFF" stroke-width="0.6" />
        </rule>
        <rule e="way" k="waterway" v="river">
            <line stroke="#B3DDFF" stroke-width="1.1" />
        </rule>
        <rule e="way" k="waterway" v="riverbank">
            <area fill="#B3DDFF" />
        </rule>
        <rule e="way" k="waterway" v="river" zoom-min="12">
