=== mapsforge/mapsforge/mapsforge-map/src/main/resources/renderTheme-v4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://mapsforge.org/renderTheme"
	xmlns:tns="http://mapsforge.org/renderTheme" elementFormDefault="qualified" xml:lang="en">
	<!-- attribute types -->
	<xs:simpleType name="cap">
		<xs:restriction base="xs:string">
			<xs:enumeration value="butt" />
			<xs:enumeration value="round" />
			<xs:enumeration value="square" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="position">
		<xs:restriction base="xs:string">
			<xs:enumeration value="auto" />
			<xs:enumeration value="center" />
			<xs:enumeration value="below" />
			<xs:enumeration value="below_left" />
			<xs:enumeration value="below_right" />
			<xs:enumeration value="above" />
			<xs:enumeration value="above_left" />
			<xs:enumeration value="above_right" />
			<xs:enumeration value="left" />
			<xs:enumeration value="right" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="closed">
		<xs:restriction base="xs:string">
			<xs:enumeration value="yes" />
			<xs:enumeration value="no" />
			<xs:enumeration value="any" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="color">
		<xs:annotation>
			<xs:documentation>Supported formats are #RRGGBB and #AARRGGBB.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="#([0-9a-fA-F]{6}|[0-9a-fA-F]{8})" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="display">
		<xs:restriction base="xs:string">
			<xs:enumeration value="always" />
			<xs:enumeration value="never" />
			<xs:enumeration value="ifspace" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="elementList">
		<xs:restriction base="xs:string">
			<xs:enumeration value="node" />
			<xs:enumeration value="way" />
			<xs:enumeration value="any" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="fontFamily">
		<xs:restriction base="xs:string">
			<xs:enumeration value="default" />
			<xs:enumeration value="monospace" />
			<xs:enumeration value="sans_serif" />
			<xs:enumeration value="serif" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="fontStyle">
		<xs:restriction base="xs:string">
			<xs:enumeration value="bold" />
			<xs:enumeration value="bold_italic" />
			<xs:enumeration value="italic" />
			<xs:enumeration value="normal" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="linejoin">
		<xs:restriction base="xs:string">
			<xs:enumeration value="miter" />
			<xs:enumeration value="round" />
			<xs:enumeration value="bevel" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="nonNegativeFloat">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="0" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="scaling">
		<xs:restriction base="xs:string">
			<xs:pattern value="(default|size|percent)" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="src">
		<xs:restriction base="xs:string">
			<xs:pattern value="(jar|file|assets):.+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="strokeDasharray">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9]+(\.[0-9]+)? *, *[0-9]+(\.[0-9]+)? *, *)*[0-9]+(\.[0-9]+)? *, *[0-9]+(\.[0-9]+)?" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="textKey">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ele" />
			<xs:enumeration value="addr:housenumber" />
			<xs:enumeration value="name" />
			<xs:enumeration value="ref" />
		</xs:restriction>
	</xs:simpleType>

 	<xs:complexType name="area">
		<xs:attribute name="cat" type="xs:string" use="optional" />
		<xs:attribute name="src" type="tns:src" use="optional" />
		<xs:attribute name="symbol-scaling" type="tns:scaling" use="optional" default="default"/>
		<xs:attribute name="symbol-width" type="xs:positiveInteger" use="optional" />
		<xs:attribute name="symbol-height" type="xs:positiveInteger" use="optional" />
		<xs:attribute name="symbol-percent" type="xs:positiveInteger" use="optional" />
		<xs:attribute name="fill" type="tns:color" use="optional" default="#000000" />
		<xs:attribute name="stroke" type="tns:color" use="optional" default="#00000000" />
		<xs:attribute name="stroke-width" type="tns:nonNegativeFloat" use="optional" default="0" />
	</xs:complexType>

	<xs:complexType name="caption">
		<xs:attribute name="cat" type="xs:string" use="optional" />
		<xs:attribute name="priority" type="xs:integer" use="optional" default="0"/>
		<xs:attribute name="k" type="tns:textKey" use="required" />
		<xs:attribute name="display" type="tns:display" use="optional" default="ifspace"/>
		<xs:attribute name="dy" type="xs:float" use="optional" default="0" />
		<xs:attribute name="font-family" type="tns:fontFamily" use="optional" default="default" />
		<xs:attribute name="font-style" type="tns:fontStyle" use="optional" default="normal" />
		<xs:attribute name="font-size" type="tns:nonNegativeFloat" use="optional" default="0" />
		<xs:attribute name="fill" type="tns:color" use="optional" default="#000000" />
		<xs:attribute name="stroke" type="tns:color" use="optional" default="#000000" />
		<xs:attribute name="stroke-width" type="tns:nonNegativeFloat" use="optional" default="0" />
		<xs:attribute name="position" type="tns:position" use="optional" default="auto" />
		<xs:attribute name="symbol-id" type="xs:string" use="optional" />
    </xs:complexType>

	<!-- style menu cat element -->
	<xs:complexType name="cat">
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

 	<xs:complexType name="circle">
		<xs:attribute name="cat" type="xs:string" use="optional" />
		<xs:attribute name="radius" type="tns:nonNegativeFloat" use="required" />
		<xs:attribute name="scale-radius" type="xs:boolean" use="optional" default="false" />
		<xs:attribute name="fill" type="tns:color" use="optional" default="#00000000" />
		<xs:attribute name="stroke" type="tns:color" use="optional" default="#00000000" />
		<xs:attribute name="stroke-width" type="tns:nonNegativeFloat" use="optional" default="0" />
	</xs:complexType>

	<!-- style menu layer element -->
	<xs:complexType name="layer">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="name" type="tns:name" />
			</xs:sequence>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="cat" type="tns:cat" />
			</xs:sequence>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="overlay" type="tns:overlay" />
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required" />
		<xs:attribute name="parent" type="xs:string" use="optional" />
		<xs:attribute name="visible" type="xs:boolean" use="optional" default="true"/>
	</xs:complexType>

	<xs:complexType name="line">
		<xs:attribute name="cat" type="xs:string" use="optional" />
		<xs:attribute name="src" type="tns:src" use="optional" />
		<xs:attribute name="symbol-scaling" type="tns:scaling" use="optional" default="default"/>
		<xs:attribute name="symbol-width" type="xs:positiveInteger" use="optional" />
		<xs:attribute name="symbol-height" type="xs:positiveInteger" use="optional" />
		<xs:attribute name="symbol-percent" type="xs:positiveInteger" use="optional" />
		<xs:attribute name="dy" type="xs:float" use="optional" default="0" />
		<xs:attribute name="stroke" type="tns:color" use="optional" default="#000000" />
		<xs:attribute name="stroke-width" type="tns:nonNegativeFloat" use="optional" default="0" />
		<xs:attribute name="stroke-dasharray" type="tns:strokeDasharray" use="optional" />
		<xs:attribute name="stroke-linecap" type="tns:cap" use="optional" default="round" />
		<xs:attribute name="stroke-linejoin" type="tns:linejoin" use="optional" default="round" />
	</xs:complexType>

	<xs:complexType name="lineSymbol">
		<xs:attribute name="cat" type="xs:string" use="optional" />
		<xs:attribute name="display" type="tns:display" use="optional" default="ifspace"/>
		<xs:attribute name="dy" type="xs:float" use="optional" default="0" />
		<xs:attribute name="src" type="tns:src" use="required" />
		<xs:attribute name="symbol-scaling" type="tns:scaling" use="optional" default="default"/>
		<xs:attribute name="symbol-width" type="xs:positiveInteger" use="optional" />
		<xs:attribute name="symbol-height" type="xs:positiveInteger" use="optional" />
		<xs:attribute name="symbol-percent" type="xs:positiveInteger" use="optional" />
		<xs:attribute name="align-center" type="xs:boolean" use="optional" default="false" />
		<xs:attribute name="priority" type="xs:integer" use="optional" default="0"/>
		<xs:attribute name="repeat" type="xs:boolean" use="optional" default="false" />
		<xs:attribute name="repeat-gap" type="xs:float" use="optional" default="200" />
		<xs:attribute name="repeat-start" type="xs:float" use="optional" default="30" />
		<xs:attribute name="rotate" type="xs:boolean" use="optional" default="true" />
	</xs:complexType>

	<!-- style menu name element -->
	<xs:complexType name="name">
		<xs:attribute name="lang" type="xs:string" use="required" />
		<xs:attribute name="value" type="xs:string" use="required" />
	</xs:complexType>

	<!-- style menu overlay element -->
	<xs:complexType name="overlay">
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="pathText">
		<xs:attribute name="cat" type="xs:string" use="optional" />
		<xs:attribute name="display" type="tns:display" use="optional" default="ifspace"/>
		<xs:attribute name="k" type="tns:textKey" use="required" />
		<xs:attribute name="dy" type="xs:float" use="optional" default="0" />
		<xs:attribute name="font-family" type="tns:fontFamily" use="optional" default="default" />
		<xs:attribute name="font-style" type="tns:fontStyle" use="optional" default="normal" />
		<xs:attribute name="font-size" type="tns:nonNegativeFloat" use="optional" default="0" />
		<xs:attribute name="fill" type="tns:color" use="optional" default="#000000" />
		<xs:attribute name="priority" type="xs:integer" use="optional" default="0"/>
		<xs:attribute name="stroke" type="tns:color" use="optional" default="#000000" />
		<xs:attribute name="stroke-width" type="tns:nonNegativeFloat" use="optional" default="0" />
	</xs:complexType>

	<xs:complexType name="symbol">
		<xs:attribute name="id" type="xs:string" use="optional" />
		<xs:attribute name="cat" type="xs:string" use="optional" />
		<xs:attribute name="display" type="tns:display" use="optional" default="ifspace"/>
		<xs:attribute name="priority" type="xs:integer" use="optional" default="0"/>
		<xs:attribute name="src" type="tns:src" use="required" />
		<xs:attribute name="symbol-scaling" type="tns:scaling" use="optional" default="default"/>
		<xs:attribute name="symbol-width" type="xs:positiveInteger" use="optional" />
		<xs:attribute name="symbol-height" type="xs:positiveInteger" use="optional" />
		<xs:attribute name="symbol-percent" type="xs:positiveInteger" use="optional" />
    </xs:complexType>

<!-- rule elements -->
	<xs:complexType name="rule">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<!-- recursion to allow for nested rules -->
			<xs:element name="rule" type="tns:rule" />
			<xs:element name="area" type="tns:area" />
			<xs:element name="caption" type="tns:caption" />
			<xs:element name="circle" type="tns:circle" />
			<xs:element name="line" type="tns:line" />
			<xs:element name="lineSymbol" type="tns:lineSymbol" />
			<xs:element name="pathText" type="tns:pathText" />
			<xs:element name="symbol" type="tns:symbol" />
		</xs:choice>
		<xs:attribute name="e" type="tns:elementList" use="required" />
		<xs:attribute name="k" type="xs:string" use="required" />
		<xs:attribute name="v" type="xs:string" use="required" />
		<xs:attribute name="cat" type="xs:string" use="optional" />
		<xs:attribute name="closed" type="tns:closed" use="optional" default="any" />
		<xs:attribute name="zoom-min" type="xs:unsignedByte" use="optional" default="0" />
		<xs:attribute name="zoom-max" type="xs:unsignedByte" use="optional" default="127" />
	</xs:complexType>


	<!-- rendertheme element -->
	<xs:complexType name="rendertheme">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="stylemenu" type="tns:stylemenu" />
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="rule" type="tns:rule" />
		    </xs:sequence>
		</xs:sequence>
		<xs:attribute name="version" type="xs:positiveInteger" fixed="4" />
		<xs:attribute name="map-background" type="tns:color" use="optional" default="#ffffff" />
		<xs:attribute name="map-background-outside" type="tns:color" use="optional" default="#ffffff" />
		<xs:attribute name="base-stroke-width" type="tns:nonNegativeFloat" use="optional" default="1" />
		<xs:attribute name="base-text-size" type="tns:nonNegativeFloat" use="optional" default="1" />
	</xs:complexType>

 	<!-- stylemenu element -->
 	<xs:complexType name="stylemenu">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="style" type="tns:layer" />
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="defaultvalue" type="xs:string" use="required" />
		<xs:attribute name="defaultlang" type="xs:string" use="optional" />
		<xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>

	<!-- root element -->
	<xs:element name="rendertheme" type="tns:rendertheme" />
</xs:schema>

=== mapsforge/mapsforge/mapsforge-map/src/main/resources/osmarender/osmarender.xml
<?xml version="1.0" encoding="UTF-8"?>
<rendertheme xmlns="http://mapsforge.org/renderTheme" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://mapsforge.org/renderTheme https://raw.githubusercontent.com/mapsforge/mapsforge/dev/resources/renderTheme-v4.xsd"
	version="4" map-background="#f8f8f8" map-background-outside="#dddddd">

	<rule e="way" k="natural" v="issea|sea">
		<area fill="#B3DDFF"/>
	</rule>

	<rule e="way" k="natural" v="nosea">
		<area fill="#F8F8F8" stroke="#F8F8F8" stroke-width="1.0"/>
	</rule>

	<!-- ways -->
	<rule e="way" k="*" v="*">
		<!-- landuse -->
		<rule e="way" k="landuse" v="*">
			<rule e="way" k="landuse" v="military">
				<area src="jar:patterns/military.png" stroke="#e4e4e4" stroke-width="0.2" />
			</rule>
			<rule e="way" k="landuse" v="residential|farmyard">
				<area fill="#e4e4e4" />
			</rule>
			<rule e="way" k="landuse" v="retail">
				<area fill="#ffebeb" stroke="#e4e4e4" stroke-width="0.2" />
			</rule>
			<rule e="way" k="landuse" v="industrial|brownfield|railway">
				<area fill="#ecd8ff" stroke="#e4e4e4" stroke-width="0.2" />
			</rule>
			<rule e="way" k="landuse" v="commercial">
				<area fill="#ffffc0" stroke="#e4e4e4" stroke-width="0.2" />
			</rule>
			<rule e="way" k="landuse" v="construction|greenfield">
				<area fill="#a47c41" stroke="#e4e4e4" stroke-width="0.2" />
			</rule>
			<rule e="way" k="landuse" v="garages">
				<area fill="#d6d6e4" />
			</rule>

			<rule e="way" k="*" v="*" zoom-min="16">
				<caption k="name" font-style="bold" font-size="10" fill="#4040ff" stroke="#ffffff" stroke-width="2.0" />
			</rule>
		</rule>


		<!-- tunnel -->
		<rule e="way" k="tunnel" v="true|yes">
			<!-- highway tunnels -->
			<rule e="way" k="highway" v="*">
				<!-- highway tunnel casings -->
				<rule e="way" k="highway" v="steps|footway|path">
					<line stroke="#707070" stroke-width="0.6" stroke-dasharray="5,5" stroke-linecap="butt" />
				</rule>
				<rule e="way" k="highway" v="track|cycleway|bridleway|service">
					<line stroke="#707070" stroke-width="1.0" stroke-dasharray="5,5" stroke-linecap="butt" />
				</rule>
				<rule e="way" k="highway" v="construction">
					<line stroke="#707070" stroke-width="1.1" stroke-dasharray="5,5" stroke-linecap="butt" />
				</rule>
				<rule e="way" k="highway" v="road">
					<line stroke="#707070" stroke-width="1.3" stroke-dasharray="5,5" stroke-linecap="butt" />
				</rule>
				<rule e="way" k="highway" v="pedestrian|unclassified|residential|living_street|byway">
					<line stroke="#707070" stroke-width="1.5" stroke-dasharray="5,5" stroke-linecap="butt" />
				</rule>
				<rule e="way" k="highway" v="tertiary|secondary_link|primary_link|trunk_link|motorway_link|secondary|primary|trunk">
					<line stroke="#707070" stroke-width="1.8" stroke-dasharray="5,5" stroke-linecap="butt" />
				</rule>
				<rule e="way" k="highway" v="motorway">
					<line stroke="#707070" stroke-width="2.0" stroke-dasharray="5,5" stroke-linecap="butt" />
				</rule>

				<!-- highway tunnel cores -->
				<rule e="way" k="highway" v="steps|footway|path">
					<line stroke="#ffffff" stroke-width="0.45" stroke-dasharray="5,5" stroke-linecap="butt" />
				</rule>
				<rule e="way" k="highway" v="track">
					<line stroke="#ffffff" stroke-width="0.7" stroke-dasharray="5,5" stroke-linecap="butt" />
				</rule>
				<rule e="way" k="highway" v="cycleway|bridleway|service">
					<line stroke="#ffffff" stroke-width="0.85" stroke-dasharray="5,5" stroke-linecap="butt" />
				</rule>
				<rule e="way" k="highway" v="construction">
					<line stroke="#ffffff" stroke-width="1.0" stroke-dasharray="5,5" stroke-linecap="butt" />
				</rule>
				<rule e="way" k="highway" v="road">
					<line stroke="#ffffff" stroke-width="1.25" stroke-dasharray="5,5" stroke-linecap="butt" />
				</rule>
				<rule e="way" k="highway" v="pedestrian|unclassified|residential|living_street|byway">
					<line stroke="#ffffff" stroke-width="1.35" stroke-dasharray="5,5" stroke-linecap="butt" />
				</rule>
				<rule e="way" k="highway" v="tertiary_link|tertiary|secondary_link|primary_link|trunk_link|motorway_link|secondary|primary|trunk">
					<line stroke="#ffffff" stroke-width="1.5" stroke-dasharray="5,5" stroke-linecap="butt" />
				</rule>
				<rule e="way" k="highway" v="motorway">
					<line stroke="#ffffff" stroke-width="1.7" stroke-dasharray="5,5" stroke-linecap="butt" />
				</rule>
			</rule>

			<!-- railway tunnel -->
			<rule e="way" k="railway" v="*">
				<rule e="way" k="railway" v="tram|subway|light_rail|narrow_gauge">
					<line stroke="#880f0f4c" stroke-width="0.25" stroke-dasharray="4,4" stroke-linecap="butt" />
				</rule>
				<rule e="way" k="railway" v="rail">
					<line stroke="#aa333333" stroke-width="0.4" stroke-dasharray="4,4" stroke-linecap="butt" />
				</rule>
			</rule>
		</rule>


		<!-- landuse -->
		<rule e="way" k="landuse" v="*">
			<rule e="way" k="landuse" v="landfill|quarry">
				<area fill="#e9dd72" stroke="#556b2f" stroke-width="0.2" />
			</rule>
			<rule e="way" k="landuse" v="cemetery">
				<area src="jar:patterns/cemetery.png" stroke="#e4e4e4" stroke-width="0.2" />
			</rule>
			<rule e="way" k="landuse" v="field|farm|farmland|meadow|grass">
				<area fill="#ebfff2" stroke="#9ee673" stroke-width="0.1" />
			</rule>
			<rule e="way" k="landuse" v="allotments|village_green|recreation_ground">
				<area fill="#bde3cb" stroke="#6fc13d" stroke-width="0.2" />
			</rule>
			<rule e="way" k="landuse" v="reservoir|basin">
				<area fill="#b5d6f1" />
			</rule>

			<rule e="way" k="*" v="*" zoom-min="16">
				<caption k="name" font-style="bold" font-size="10" fill="#4040ff" stroke="#ffffff" stroke-width="2.0" />
			</rule>
		</rule>


		<rule e="way" k="natural|landuse" v="forest|wood|scrub">
			<rule e="way" k="wood" v="*">
				<rule e="way" k="wood" v="coniferous">
					<area src="jar:patterns/wood-coniferous.png" />
				</rule>
				<rule e="way" k="wood" v="deciduous">
					<area src="jar:patterns/wood-deciduous.png" />
				</rule>
				<rule e="way" k="wood" v="mixed">
					<area src="jar:patterns/wood-mixed.png" />
				</rule>
			</rule>
			<rule e="way" k="wood" v="~">
				<area fill="#6fc18e" stroke="#6fc18e" stroke-width="0.2" />
			</rule>

			<rule e="way" k="*" v="*" zoom-min="16">
				<caption k="name" font-style="bold" font-size="10" fill="#4040ff" stroke="#ffffff" stroke-width="2.0" />
			</rule>
		</rule>


		<!-- amenity -->
		<rule e="way" k="amenity" v="*">
			<rule e="way" k="amenity" v="kindergarten|school|college|university">
				<area fill="#cdabde" stroke="#e9dd72" stroke-width="0.2" />
			</rule>
			<rule e="way" k="amenity" v="grave_yard">
				<area src="jar:patterns/cemetery.png" stroke="#e4e4e4" stroke-width="0.2" />
			</rule>
			<rule e="way" k="amenity" v="parking">
				<area fill="#ffffc0" stroke="#e9dd72" stroke-width="0.2" />
				<rule e="way" k="access" v="private" zoom-min="15">
					<area src="jar:patterns/access-private.png" />
				</rule>
				<rule e="way" k="*" v="*" zoom-min="17">
					<symbol src="jar:symbols/parking.svg" />
				</rule>
			</rule>
			<rule e="way" k="amenity" v="fountain" closed="yes">
				<area fill="#b5d6f1" stroke="#000080" stroke-width="0.15" />
				<rule e="way" k="*" v="*" zoom-min="17">
					<symbol src="jar:symbols/fountain.svg" />
				</rule>
			</rule>
			<rule e="way" k="amenity" v="hospital" zoom-min="15">
				<symbol src="jar:symbols/hospital.svg" />
			</rule>
			<rule e="way" k="amenity" v="theatre" zoom-min="17">
				<symbol src="jar:symbols/theatre.svg" />
			</rule>
			<rule e="way" k="amenity" v="toilets" zoom-min="17">
				<symbol src="jar:symbols/toilets.svg" />
			</rule>

			<rule e="way" k="*" v="*" zoom-min="17">
				<caption k="name" font-style="bold" font-size="10" fill="#4040ff" stroke="#ffffff" stroke-width="2.0" />
			</rule>
		</rule>


		<!-- natural -->
		<rule e="way" k="natural" v="*">
			<rule e="way" k="natural" v="glacier">
				<area fill="#fafaff" stroke="#add8e6" stroke-width="0.8" />
			</rule>
			<rule e="way" k="natural" v="land">
				<area fill="#f8f8f8" stroke="#e0e0e0" stroke-width="0.1" />
			</rule>
			<rule e="way" k="natural" v="beach">
				<area fill="#eecc55" />
			</rule>
			<rule e="way" k="natural" v="heath">
				<area fill="#ffffc0" stroke="#ffff90" stroke-width="0.2" />
			</rule>
			<rule e="way" k="natural" v="marsh|wetland">
				<area src="jar:patterns/marsh.png" />
			</rule>

			<rule e="way" k="*" v="*" zoom-min="16">
				<caption k="name" font-style="bold" font-size="10" fill="#4040ff" stroke="#ffffff" stroke-width="2.0" />
			</rule>
		</rule>


		<!-- leisure -->
		<rule e="way" k="leisure" v="*">
			<rule e="way" k="leisure" v="park|garden|golf_course|common|green">
				<area fill="#c7f1a3" stroke="#6fc18e" stroke-width="0.2" />
			</rule>
			<rule e="way" k="leisure" v="playground|playing_fields|pitch|dog_park">
				<area fill="#c7f1a3" stroke="#6fc18e" stroke-width="0.2" />
				<rule e="way" k="*" v="playground" zoom-min="17">
					<symbol src="jar:symbols/playground.svg" />
				</rule>
			</rule>
			<rule e="way" k="leisure" v="nature_reserve">
				<area src="jar:patterns/nature-reserve.png" stroke="#6fc18e" stroke-width="0.2" />
			</rule>

			<rule e="way" k="leisure" v="stadium|sports_centre|water_park">
				<area fill="#bde3cb" stroke="#6fc18e" stroke-width="0.2" />
			</rule>
			<rule e="way" k="leisure" v="track">
				<rule e="way" k="area" v="yes|true">
					<area fill="#bde3cb" stroke="#6fc18e" stroke-width="0.025" />
				</rule>
				<rule e="way" k="area" v="~|no|false">
					<line stroke="#6fc18e" stroke-width="0.75" />
					<line stroke="#bde3cb" stroke-width="0.7" />
				</rule>
			</rule>
			<rule e="way" k="leisure" v="swimming_pool">
				<area fill="#b5d6f1" stroke="#6060ff" stroke-width="0.2" />
			</rule>

			<rule e="way" k="*" v="*" zoom-min="16">
				<caption k="name" font-style="bold" font-size="10" fill="#4040ff" stroke="#ffffff" stroke-width="2.0" />
			</rule>
		</rule>
