=== mapsforge/mapsforge/mapsforge-map/src/main/resources/renderTheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://mapsforge.org/renderTheme"
	xmlns:tns="http://mapsforge.org/renderTheme" elementFormDefault="qualified" xml:lang="en">
	<!-- attribute types -->
	<xs:simpleType name="cap">
		<xs:restriction base="xs:string">
			<xs:enumeration value="butt" />
			<xs:enumeration value="round" />
			<xs:enumeration value="square" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="closed">
		<xs:restriction base="xs:string">
			<xs:enumeration value="yes" />
			<xs:enumeration value="no" />
			<xs:enumeration value="any" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="color">
		<xs:restriction base="xs:string">
			<xs:pattern value="#([0-9a-fA-F]{6}|[0-9a-fA-F]{8})" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="elementList">
		<xs:restriction base="xs:string">
			<xs:enumeration value="node" />
			<xs:enumeration value="way" />
			<xs:enumeration value="any" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="fontFamily">
		<xs:restriction base="xs:string">
			<xs:enumeration value="default" />
			<xs:enumeration value="default_bold" />
			<xs:enumeration value="monospace" />
			<xs:enumeration value="sans_serif" />
			<xs:enumeration value="serif" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="fontStyle">
		<xs:restriction base="xs:string">
			<xs:enumeration value="bold" />
			<xs:enumeration value="bold_italic" />
			<xs:enumeration value="italic" />
			<xs:enumeration value="normal" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="nonNegativeFloat">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="0" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="src">
		<xs:restriction base="xs:string">
			<xs:pattern value="(jar|file)\:.+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="strokeDasharray">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9]+(\.[0-9]+)? *, *[0-9]+(\.[0-9]+)? *, *)*[0-9]+(\.[0-9]+)? *, *[0-9]+(\.[0-9]+)?" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="textKey">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ele" />
			<xs:enumeration value="addr:housenumber" />
			<xs:enumeration value="name" />
			<xs:enumeration value="ref" />
		</xs:restriction>
	</xs:simpleType>


	<!-- rendering instructions -->
	<xs:complexType name="area">
		<xs:attribute name="src" type="tns:src" use="optional" />
		<xs:attribute name="fill" type="tns:color" use="optional" default="#000000" />
		<xs:attribute name="stroke" type="tns:color" use="optional" default="#00000000" />
		<xs:attribute name="stroke-width" type="tns:nonNegativeFloat" use="optional" default="0" />
	</xs:complexType>

	<xs:complexType name="caption">
		<xs:attribute name="k" type="tns:textKey" use="required" />
		<xs:attribute name="dy" type="xs:float" use="optional" default="0" />
		<xs:attribute name="font-family" type="tns:fontFamily" use="optional" default="default" />
		<xs:attribute name="font-style" type="tns:fontStyle" use="optional" default="normal" />
		<xs:attribute name="font-size" type="tns:nonNegativeFloat" use="optional" default="0" />
		<xs:attribute name="fill" type="tns:color" use="optional" default="#000000" />
		<xs:attribute name="stroke" type="tns:color" use="optional" default="#000000" />
		<xs:attribute name="stroke-width" type="tns:nonNegativeFloat" use="optional" default="0" />
	</xs:complexType>

	<xs:complexType name="circle">
		<xs:attribute name="radius" type="tns:nonNegativeFloat" use="required" />
		<xs:attribute name="scale-radius" type="xs:boolean" use="optional" default="false" />
		<xs:attribute name="fill" type="tns:color" use="optional" default="#00000000" />
		<xs:attribute name="stroke" type="tns:color" use="optional" default="#00000000" />
		<xs:attribute name="stroke-width" type="tns:nonNegativeFloat" use="optional" default="0" />
	</xs:complexType>

	<xs:complexType name="line">
		<xs:attribute name="src" type="tns:src" use="optional" />
		<xs:attribute name="stroke" type="tns:color" use="optional" default="#000000" />
		<xs:attribute name="stroke-width" type="tns:nonNegativeFloat" use="optional" default="0" />
		<xs:attribute name="stroke-dasharray" type="tns:strokeDasharray" use="optional" />
		<xs:attribute name="stroke-linecap" type="tns:cap" use="optional" default="round" />
	</xs:complexType>

	<xs:complexType name="lineSymbol">
		<xs:attribute name="src" type="tns:src" use="required" />
		<xs:attribute name="align-center" type="xs:boolean" use="optional" default="false" />
		<xs:attribute name="repeat" type="xs:boolean" use="optional" default="false" />
	</xs:complexType>

	<xs:complexType name="pathText">
		<xs:attribute name="k" type="tns:textKey" use="required" />
		<xs:attribute name="font-family" type="tns:fontFamily" use="optional" default="default" />
		<xs:attribute name="font-style" type="tns:fontStyle" use="optional" default="normal" />
		<xs:attribute name="font-size" type="tns:nonNegativeFloat" use="optional" default="0" />
		<xs:attribute name="fill" type="tns:color" use="optional" default="#000000" />
		<xs:attribute name="stroke" type="tns:color" use="optional" default="#000000" />
		<xs:attribute name="stroke-width" type="tns:nonNegativeFloat" use="optional" default="0" />
	</xs:complexType>

	<xs:complexType name="symbol">
		<xs:attribute name="src" type="tns:src" use="required" />
	</xs:complexType>


	<!-- rule elements -->
	<xs:complexType name="rule">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<!-- recursion to allow for nested rules -->
			<xs:element name="rule" type="tns:rule" />

			<xs:element name="area" type="tns:area" />
			<xs:element name="caption" type="tns:caption" />
			<xs:element name="circle" type="tns:circle" />
			<xs:element name="line" type="tns:line" />
			<xs:element name="lineSymbol" type="tns:lineSymbol" />
			<xs:element name="pathText" type="tns:pathText" />
			<xs:element name="symbol" type="tns:symbol" />
		</xs:choice>
		<xs:attribute name="e" type="tns:elementList" use="required" />
		<xs:attribute name="k" type="xs:string" use="required" />
		<xs:attribute name="v" type="xs:string" use="required" />
		<xs:attribute name="closed" type="tns:closed" use="optional" default="any" />
		<xs:attribute name="zoom-min" type="xs:unsignedByte" use="optional" default="0" />
		<xs:attribute name="zoom-max" type="xs:unsignedByte" use="optional" default="127" />
	</xs:complexType>


	<!-- rendertheme element -->
	<xs:complexType name="rendertheme">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="rule" type="tns:rule" />
		</xs:sequence>
		<xs:attribute name="version" type="xs:positiveInteger" use="required" />
		<xs:attribute name="map-background" type="tns:color" use="optional" default="#ffffff" />
		<xs:attribute name="base-stroke-width" type="tns:nonNegativeFloat" use="optional" default="1" />
		<xs:attribute name="base-text-size" type="tns:nonNegativeFloat" use="optional" default="1" />
	</xs:complexType>


	<!-- root element -->
	<xs:element name="rendertheme" type="tns:rendertheme" />
</xs:schema>

=== mapsforge/mapsforge/Applications/Android/Samples/data/onlylanduse.xml
<?xml version="1.0" encoding="UTF-8"?>
<rendertheme xmlns="http://mapsforge.org/renderTheme" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://mapsforge.org/renderTheme https://raw.githubusercontent.com/mapsforge/mapsforge/dev/resources/renderTheme.xsd"
	version="3" map-background="#00000000">

	<!-- ways -->
	<rule e="way" k="*" v="*">
		<!-- landuse -->
		<rule e="way" k="landuse" v="*">
			<rule e="way" k="landuse" v="military">
				<area src="jar:patterns/military.png" stroke="#e4e4e4" stroke-width="0.2" />
			</rule>
			<rule e="way" k="landuse" v="residential|farmyard">
				<area fill="#e4e4e4" />
			</rule>
			<rule e="way" k="landuse" v="retail">
				<area fill="#ffebeb" stroke="#e4e4e4" stroke-width="0.2" />
			</rule>
			<rule e="way" k="landuse" v="industrial|brownfield|railway">
				<area fill="#ecd8ff" stroke="#e4e4e4" stroke-width="0.2" />
			</rule>
			<rule e="way" k="landuse" v="commercial">
				<area fill="#ffffc0" stroke="#e4e4e4" stroke-width="0.2" />
			</rule>
			<rule e="way" k="landuse" v="construction|greenfield">
				<area fill="#a47c41" stroke="#e4e4e4" stroke-width="0.2" />
			</rule>
			<rule e="way" k="landuse" v="garages">
				<area fill="#d6d6e4" />
			</rule>

			<rule e="way" k="*" v="*" zoom-min="16">
				<caption k="name" font-style="bold" font-size="10" fill="#4040ff" stroke="#ffffff" stroke-width="2.0" />
			</rule>
		</rule>



		<!-- landuse -->
		<rule e="way" k="landuse" v="*">
			<rule e="way" k="landuse" v="landfill|quarry">
				<area fill="#e9dd72" stroke="#556b2f" stroke-width="0.2" />
			</rule>
			<rule e="way" k="landuse" v="cemetery">
				<area src="jar:patterns/cemetery.png" stroke="#e4e4e4" stroke-width="0.2" />
			</rule>
			<rule e="way" k="landuse" v="field|farm|farmland|meadow|grass">
				<area fill="#ebfff2" stroke="#9ee673" stroke-width="0.1" />
			</rule>
			<rule e="way" k="landuse" v="allotments|village_green|recreation_ground">
				<area fill="#bde3cb" stroke="#6fc13d" stroke-width="0.2" />
			</rule>
			<rule e="way" k="landuse" v="reservoir|basin">
				<area fill="#b5d6f1" />
			</rule>

			<rule e="way" k="*" v="*" zoom-min="16">
				<caption k="name" font-style="bold" font-size="10" fill="#4040ff" stroke="#ffffff" stroke-width="2.0" />
			</rule>
		</rule>


		<rule e="way" k="natural|landuse" v="forest|wood|scrub">
			<rule e="way" k="wood" v="*">
				<rule e="way" k="wood" v="coniferous">
					<area src="jar:patterns/wood-coniferous.png" />
				</rule>
				<rule e="way" k="wood" v="deciduous">
					<area src="jar:patterns/wood-deciduous.png" />
				</rule>
				<rule e="way" k="wood" v="mixed">
					<area src="jar:patterns/wood-mixed.png" />
				</rule>
			</rule>
			<rule e="way" k="wood" v="~">
				<area fill="#6fc18e" stroke="#6fc18e" stroke-width="0.2" />
			</rule>

			<rule e="way" k="*" v="*" zoom-min="16">
				<caption k="name" font-style="bold" font-size="10" fill="#4040ff" stroke="#ffffff" stroke-width="2.0" />
			</rule>
		</rule>
		
		<!-- building -->
		<rule e="way" k="building" v="*">
			<area fill="#f3d6b6" stroke="#6a5a8e" stroke-width="0.2" />

			<rule e="way" k="*" v="*" zoom-min="17">
				<caption k="name" font-style="bold" font-size="10" fill="#4040ff" stroke="#ffffff" stroke-width="2.0" />
				<caption k="addr:housenumber" font-style="bold" font-size="10" fill="#606060" stroke="#ffffff" stroke-width="2.0" />
			</rule>
		</rule>
		
	</rule>
	
	
</rendertheme>
