=== mapsforge/mapsforge/mapsforge-map-writer/src/main/resources/tag-mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://mapsforge.org/tag-mapping"
	xmlns:tns="http://mapsforge.org/tag-mapping" elementFormDefault="qualified">

	<complexType name="osm-tag">
		<annotation>
			<documentation>
				The osm-tag represents an OpenStreetMap tag and may
				refer to either a POI tag or a way tag. The required
				attributes 'key' and 'value' determine the OpenStreetMap
				tag.
				The optional attribute 'zoom-appear' defines the zoom level on
				which the tag is included in the map tile data.
				The optional attribute 'enabled' specifies whether the osm-tag
				is recognized during the map generation process (enabled by
				default) or if it is completely omitted in the map data.
				The optional attribute 'renderable' (enabled by default)
				effectively allows tags to inherit zoom-appear values from
				other tags.
			</documentation>
		</annotation>
		<sequence>
			<element name="zoom-override" type="tns:simple-tag"
				maxOccurs="unbounded" minOccurs="0">
			</element>
		</sequence>
		<attribute name="key" use="required">
			<annotation>
				<documentation>
					The key of the OpenStreetMap tag. E.g. 'highway' in
					the tag 'highway=primary'.
				</documentation>
			</annotation>
			<simpleType>
				<restriction base="string">
					<minLength value="1"></minLength>
					<maxLength value="100"></maxLength>
					<whiteSpace value="collapse"></whiteSpace>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="value" use="required">
			<annotation>
				<documentation>
					The value of the OpenStreetMap tag. E.g. 'primary'
					in the tag 'highway=primary'.
				</documentation>
			</annotation>
			<simpleType>
				<restriction base="string">
					<maxLength value="100"></maxLength>
					<minLength value="1"></minLength>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="zoom-appear" use="optional" default="17">
			<annotation>
				<documentation>
					The zoom level on which the tag should first appear
					on the map.
				</documentation>
			</annotation>
			<simpleType>
				<restriction base="int">
					<minInclusive value="0"></minInclusive>
					<maxInclusive value="21"></maxInclusive>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="enabled" type="boolean" use="optional"
			default="true">
			<annotation>
				<documentation>
					Enables or Disables the tag in the map generation
					process.

					Disabling a tag forces the map writer not to include
					the OpenStreetMap tag type in the generated map data.
					Disabling a tag overrides zoom level specific appearance
					properties of the tag.

					If the attribute is omitted on an osm-tag element, which
					is NOT part of a tag-group, this is equivalent to
					enabled='true'.

					If the attribute is omitted on a tag element, which IS
					part of a tag-group, the value of the attribute is
					derived from the tag-group's 'enabled' attribute value.
				</documentation>
			</annotation>
		</attribute>
		<attribute name="renderable" type="boolean" use="optional"
			default="true">
			<annotation>
				<documentation>
					Indicates whether the tag is renderable. Omitting
					the attribute indicates that the tag is renderable.

					During the map generation process, the minimum zoom
					level is calculated on which a way (or POI) is to be
					included in a tile. The minimum zoom level is derived
					from the lowest tag's 'zoom-appear' value of all
					renderable tags assigned to a way (or POI). A non
					renderable OpenStreetMap tag is not considered while
					looking for the lowest zoom level.

					A typical non renderable OpenStreetMap tag is 'access'.
					A way with a given 'access' value has no useful
					representation as long as there is no renderable tag
					present on the same object (e.g. highway). So the minimum
					zoom level in which the access tag is included, is
					automatically derived from the renderable tags of the
					same OpenStreetMap object (here: highway).
				</documentation>
			</annotation>
		</attribute>
		<attribute name="force-polygon-line" type="boolean" default="false">
			<annotation>
				<documentation>
					Indicates whether a closed polygon should be interpreted
					as a polyline or area. For example, important for correct
					clipping if the geometry completely covers a tile.
				</documentation>
			</annotation>
		</attribute>
		<attribute name="equivalent-values" type="string" use="optional">
			<annotation>
				<documentation>
					The usage of some tags such as "oneway" is quite
					inconsistent in the OSM dataset. Expressions such as
					"oneway=yes", "oneway=1" or oneway="true" are
					semantically equivalent. This attribute allows to
					associate these equivalent values to the single
					canonical value defined in the "value-attribute".
				</documentation>
			</annotation>
		</attribute>
	</complexType>

	<complexType name="tag-group">
		<annotation>
			<documentation>
				A tag-group clusters an arbitrary number of osm-tags. It
				takes the optional boolean attribute 'enabled' which
				allows to specify whether the group of osm-tags is used
				in the map file generation process.
			</documentation>
		</annotation>
		<sequence>
			<element name="osm-tag" type="tns:osm-tag" maxOccurs="unbounded"
				minOccurs="1">
				<annotation>
					<documentation>
						The osm-tag represents an OpenStreetMap tag and
						may refer to either a POI tag or a way tag.
					</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="enabled" type="boolean" use="optional"
			default="true">
			<annotation>
				<documentation>
					Sets the default value of the 'enabled' attribute for
					all osm-tag elements in this tag-group.

					Disabling a tag forces the map writer not to include
					the OpenStreetMap tag type in the generated map data.
					Disabling a tag overrides zoom level specific appearance
					of a tag.

					If the attribute is omitted on a tag-group element,
					this is equivalent to setting enabled='true'.

					The 'enabled' value of the tag-group can be overridden
					by each osm-tag element inside the group
					(see osm-tag.enabled).
				</documentation>
			</annotation>
		</attribute>
	</complexType>

	<complexType name="tag-mapping">
		<sequence>
			<element name="pois" type="tns:tag-group" maxOccurs="unbounded"
				minOccurs="0">
				<annotation>
					<documentation>
						A group of osm-tags referring to POIs.
					</documentation>
				</annotation>
			</element>
			<element name="ways" type="tns:tag-group" maxOccurs="unbounded"
				minOccurs="0">
				<annotation>
					<documentation>
						A group of osm-tags referring to ways.
					</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="default-zoom-appear" use="required">
			<annotation>
				<documentation>
					The default zoom-appear level that is used if the attribute
					'zoom-appear' is omitted in an osm-tag.
				</documentation>
			</annotation>
			<simpleType>
				<restriction base="int">
					<minInclusive value="0"></minInclusive>
					<maxInclusive value="21"></maxInclusive>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="profile-name" use="required">
			<annotation>
				<documentation>
					The name of this tag mapping profile. The name is attached
					to the comment field in the map file.
				</documentation>
			</annotation>
			<simpleType>
				<restriction base="string">
					<minLength value="3"></minLength>
					<maxLength value="100"></maxLength>
					<whiteSpace value="collapse"></whiteSpace>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<element name="tag-mapping" type="tns:tag-mapping">
		<annotation>
			<documentation>
				A tag-mapping specifies which OpenStreetMap tags for POIs and
				ways should be recognized by the map file generator. Mappings
				for POIs and ways may be grouped be using the pois tag or the
				ways tag, respectively.
				A tag-mapping takes as required attributes a
				default-zoom-appear value and a profile name.
				The default-zoom-appear attribute specifies which zoom-appear
				value is attributed to osm-tags which are missing the
				zoom-appear attribute.
				The profile attribute is an arbitrary name that is attached to
				the comment field in the map file.
			</documentation>
		</annotation>
	</element>

	<complexType name="simple-tag">
		<attribute name="key" use="required">
			<simpleType>
				<restriction base="string">
					<minLength value="1"></minLength>
					<maxLength value="100"></maxLength>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="value" use="required">
			<simpleType>
				<restriction base="string">
					<minLength value="1"></minLength>
					<maxLength value="100"></maxLength>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>
</schema>

=== mapsforge/mapsforge/mapsforge-map-writer/src/main/config/tag-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<tag-mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" default-zoom-appear="16"
             profile-name="default-profile" xmlns="http://mapsforge.org/tag-mapping"
             xsi:schemaLocation="http://mapsforge.org/tag-mapping https://raw.githubusercontent.com/mapsforge/mapsforge/master/resources/tag-mapping.xsd">

    <!-- ************* POIS *************** -->

    <!-- HIGHWAY TAGS -->
    <pois>
        <osm-tag key="highway" value="bus_stop" zoom-appear="17"/>
        <osm-tag key="highway" value="mini_roundabout" zoom-appear="17"/>
        <osm-tag key="highway" value="traffic_signals" zoom-appear="17"/>
        <osm-tag key="highway" value="turning_circle" zoom-appear="15"/>
        <osm-tag key='highway' value='motorway_junction' zoom-appear='14'/>
    </pois>

    <!-- MOTORCYCLE TAGS -->
    <pois>
        <osm-tag key="shop" value="motorcycle" zoom-appear="10"/>
        <osm-tag key="shop" value="motorcycle_repair" zoom-appear="10"/>
        <osm-tag key="mountain_pass" value="yes" zoom-appear="10"/>
        <osm-tag key="amenity" value="fuel" zoom-appear="10"/>
        <osm-tag key="amenity" value="charging_station" equivalent-values="ev_charging" zoom-appear="10"/>
        <osm-tag key="amenity" value="motorcycle_parking" zoom-appear="10"/>
        <osm-tag key="tourism" value="viewpoint" zoom-appear="10"/>
        <osm-tag key="tourism" value="attraction" zoom-appear="10"/>
        <osm-tag key="tourism" value="picnic_site" zoom-appear="10"/>
        <osm-tag key="historic" value="castle" zoom-appear="10"/>
    </pois>
    <!-- Potentially Important for Motorcyclists -->
    <pois>
        <osm-tag key="amenity" value="drinking_water" zoom-appear="10"/>
        <osm-tag key="amenity" value="hospital" zoom-appear="10"/>
        <osm-tag key="shop" value="mall" zoom-appear="10"/>
        <osm-tag key="shop" value="supermarket" zoom-appear="10"/>
        <osm-tag key="amenity" value="pharmacy" zoom-appear="10"/>
        <osm-tag key="amenity" value="restaurant" zoom-appear="10"/>
        <osm-tag key="amenity" value="pub" zoom-appear="10"/>
        <osm-tag key="amenity" value="cafe" zoom-appear="10"/>
        <osm-tag key="amenity" value="fast_food" zoom-appear="10"/>
        <osm-tag key="amenity" value="atm" zoom-appear="10"/>
        <osm-tag key="amenity" value="bank" zoom-appear="10"/>
        <osm-tag key="amenity" value="shelter" zoom-appear="10"/>
    </pois>

    <!-- PUBLIC AMENITIES -->
    <pois>
        <osm-tag key="amenity" value="bar" zoom-appear="17"/>
        <osm-tag key="amenity" value="bench" zoom-appear="17"/>
        <osm-tag key="amenity" value="bicycle_rental" zoom-appear="17"/>
        <osm-tag key="amenity" value="bus_station" zoom-appear="15"/>
        <osm-tag key="amenity" value="cinema" zoom-appear="17"/>
        <osm-tag key="amenity" value="fountain" zoom-appear="17"/>
        <osm-tag key="amenity" value="fire_station" zoom-appear="17"/>
        <osm-tag key="amenity" value="grave_yard" zoom-appear="15"/>
        <osm-tag key="amenity" value="kindergarten" zoom-appear="17"/>
        <osm-tag key="amenity" value="library" zoom-appear="17"/>
        <osm-tag key="amenity" value="parking" zoom-appear="14"/>
        <osm-tag key="amenity" value="place_of_worship" zoom-appear="17"/>
        <osm-tag key="amenity" value="police" zoom-appear="16"/>
        <osm-tag key="amenity" value="post_box" zoom-appear="17"/>
        <osm-tag key="amenity" value="post_office" zoom-appear="17"/>
        <osm-tag key="amenity" value="recycling" zoom-appear="17"/>
        <osm-tag key="amenity" value="school" zoom-appear="17"/>
        <osm-tag key="amenity" value="telephone" zoom-appear="17"/>
        <osm-tag key="amenity" value="theatre" zoom-appear="17"/>
        <osm-tag key="amenity" value="townhall" zoom-appear="17"/>
        <osm-tag key="amenity" value="toilets" zoom-appear="17"/>
        <osm-tag key="amenity" value="university" zoom-appear="17"/>

        <osm-tag key="emergency" value="phone" zoom-appear="16"/>

        <osm-tag key="leisure" value="playground" zoom-appear="17"/>
        <osm-tag key="leisure" value="slipway" zoom-appear="17"/>

        <osm-tag key="religion" renderable="false" value="christian"/>
        <osm-tag key="religion" renderable="false" value="jewish"/>
        <osm-tag key="religion" renderable="false" value="muslim"/>

        <osm-tag key="shop" value="bakery" zoom-appear="17"/>
        <osm-tag key="shop" value="bicycle" zoom-appear="17"/>
        <osm-tag key="shop" value="hairdresser" zoom-appear="17"/>
        <osm-tag key="shop" value="laundry" zoom-appear="17"/>
        <osm-tag key="shop" value="organic" zoom-appear="17"/>
    </pois>

    <!-- PUBLIC TRANSPORT TAGS -->
    <pois>
        <osm-tag key="railway" value="halt" zoom-appear="16"/>
        <osm-tag key="railway" value="level_crossing" zoom-appear="16"/>
        <osm-tag key="railway" value="station" zoom-appear="14"/>
        <osm-tag key="railway" value="tram_stop" zoom-appear="16"/>

        <osm-tag key="station" value="light_rail" zoom-appear="15">
            <zoom-override key="railway" value="station"/>
        </osm-tag>
        <osm-tag key="station" value="subway" zoom-appear="15">
            <zoom-override key="railway" value="station"/>
        </osm-tag>
    </pois>

    <!-- TOURISM TAGS -->
    <pois>
        <osm-tag key="tourism" value="alpine_hut" zoom-appear="15"/>
        <osm-tag key='tourism' value='camp_site' zoom-appear='12' />
        <osm-tag key='tourism' value='caravan_site' zoom-appear='12' />
        <osm-tag key="tourism" value="hostel" zoom-appear="15"/>
        <osm-tag key="tourism" value="hotel" zoom-appear="15"/>
        <osm-tag key="tourism" value="information" zoom-appear="17"/>
        <osm-tag key="tourism" value="museum" zoom-appear="17"/>

        <osm-tag key="historic" value="memorial" zoom-appear="17"/>
        <osm-tag key="historic" value="monument" zoom-appear="17"/>
    </pois>

    <!-- PLACES TAGS -->
    <pois>
        <osm-tag key="place" value="city" zoom-appear="6"/>
        <osm-tag key="place" value="country" zoom-appear="3"/>
        <osm-tag key="place" value="hamlet" zoom-appear="12"/>
        <osm-tag key="place" value="island" zoom-appear="8"/>
        <osm-tag key="place" value="islet" zoom-appear="8"/>
        <osm-tag key="place" value="locality" zoom-appear="12"/>
        <osm-tag key="place" value="suburb" zoom-appear="11"/>
        <osm-tag key="place" value="town" zoom-appear="9"/>
        <osm-tag key="place" value="village" zoom-appear="11"/>
    </pois>

    <!-- NATURAL TAGS -->
    <pois>
        <osm-tag key="natural" value="cave_entrance" zoom-appear="14"/>
        <osm-tag key="natural" value="peak" zoom-appear="12"/>
        <osm-tag key="natural" value="spring" zoom-appear="17"/>
        <osm-tag key="natural" value="volcano" zoom-appear="12"/>
    </pois>

    <!-- OTHER POIS -->
    <pois>
        <osm-tag key="barrier" value="bollard" zoom-appear="17"/>
        <osm-tag key="barrier" value="cycle_barrier" zoom-appear="17"/>
        <osm-tag key="barrier" value="gate" zoom-appear="15"/>
        <osm-tag key="barrier" value="lift_gate" zoom-appear="15"/>
        <osm-tag key="barrier" value="toll_booth" zoom-appear="15"/>

        <osm-tag key="man_made" value="lighthouse" zoom-appear="17"/>
        <osm-tag key="man_made" value="surveillance" zoom-appear="17"/>
        <osm-tag key="man_made" value="tower" zoom-appear="17"/>
        <osm-tag key="man_made" value="windmill" zoom-appear="17"/>

        <osm-tag key="power" value="generator" zoom-appear="17"/>
        <osm-tag key="power" value="tower" zoom-appear="17"/>
    </pois>

    <!-- AIRPORT TAGS -->
    <pois>
        <osm-tag key="aeroway" value="aerodrome" zoom-appear="13"/>
        <osm-tag key="aeroway" value="airport" zoom-appear="13"/>
        <osm-tag key="aeroway" value="gate" zoom-appear="17"/>
        <osm-tag key="aeroway" value="helipad" zoom-appear="17"/>
    </pois>


    <!-- ************* WAYS *************** -->

    <!-- HIGHWAY TAGS -->
    <ways>
        <osm-tag key="highway" value="bridleway" zoom-appear="13"/>
        <osm-tag key="highway" value="bus_guideway" zoom-appear="13"/>
        <osm-tag key="highway" value="byway" zoom-appear="13"/>
        <osm-tag key="highway" value="construction" zoom-appear="13"/>
        <osm-tag key="highway" value="cycleway" zoom-appear="13"/>
        <osm-tag key="highway" value="footway" zoom-appear="13"/>
        <osm-tag key="highway" value="living_street" zoom-appear="13"/>
        <osm-tag key="highway" value="motorway" zoom-appear="6"/>
        <osm-tag key="highway" value="motorway_link" zoom-appear="6"/>
        <osm-tag key="highway" value="path" zoom-appear="14"/>
        <osm-tag key="highway" value="pedestrian" zoom-appear="14"/>
        <osm-tag key="highway" value="primary" zoom-appear="8"/>
        <osm-tag key="highway" value="primary_link" zoom-appear="8"/>
        <osm-tag key="highway" value="raceway" zoom-appear="12"/>
        <osm-tag key="highway" value="residential" zoom-appear="12"/>
        <osm-tag key="highway" value="road" zoom-appear="12"/>
        <osm-tag key="highway" value="secondary" zoom-appear="9"/>
        <osm-tag key="highway" value="secondary_link" zoom-appear="9"/>
        <osm-tag key="highway" value="service" zoom-appear="14"/>
        <osm-tag key="highway" value="services" zoom-appear="14"/>
        <osm-tag key="highway" value="steps" zoom-appear="16"/>
        <osm-tag key="highway" value="tertiary" zoom-appear="10"/>
        <osm-tag key="highway" value="tertiary_link" zoom-appear="10"/>
        <osm-tag key="highway" value="track" zoom-appear="12"/>
        <osm-tag key="highway" value="trunk" zoom-appear="6"/>
        <osm-tag key="highway" value="trunk_link" zoom-appear="6"/>
        <osm-tag key="highway" value="unclassified" zoom-appear="11"/>
    </ways>
